name: Deploy Shopper Agent (Cora)

on:
  push:
    # Paths include the initializer, prompt, workflow, and any associated tools
    paths:
      - 'src/app/agents/shopperAgent_initializer.py'
      - 'src/app/tools/aiSearchTools.py'
      - 'src/prompts/ShopperAgentPrompt.txt'
      - '.github/workflows/deploy-shopper-agent.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-shopper-agent:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: 'echo "$ENV" > src/.env'
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Login via Azure CLI
        uses: azure/login@v2.1.1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run shopper agent initializer
        run: |
          cd src
          python app/agents/shopperAgent_initializer.py
